### ISSUE TITLE
Misleading sentence in README

### ISSUE THREAD

**Issue by nupurgrover** [queueit/KnownUser.V3.Javascript#2]
I see in [this commit](https://github.com/queueit/KnownUser.V3.Javascript/commit/cc55565cf7e9333aeaebb2e287506e9a517f3d8a#diff-04c6e90faac2675aa89e2176d2eec7d8) that the usage of `KnownUser` SDK was removed. However, [the implementation section in the README](https://github.com/queueit/KnownUser.V3.Javascript/blob/master/README.md#implementation) still refers to the SDK and usage of `node-import` which is quite confusing. 

Do you accept PR's? If yes, I'm more than happy to submit one.

**Comment by sarooghi** [comment]
Yes please, go ahead with the pull request that would be great

**Comment by nupurgrover** [comment]
Here you go - https://github.com/queueit/KnownUser.V3.Javascript/pull/4
