### ISSUE TITLE
Missing method in sample HttpContextProvider implementation

### ISSUE THREAD

**Issue by nupurgrover** [queueit/KnownUser.V3.Javascript#3]
I am using this library with Typescript, and imported the types for `HttpContextProvider` from the `dist` folder. I noticed that the interface `IHttpContextProvider` has a `getRequestBodyAsString` method, but it is missing from the sample implementation of `initializeExpressHttpContextProvider` in the README. It's simple enough to add, so if you accept PR's, I'm happy to submit one.

**Comment by sarooghi** [comment]
yes, please pull requests are welcome

**Comment by frwiqueueit** [comment]
Its an advanced feature, described here:
https://github.com/queueit/KnownUser.V3.Javascript#request-body-trigger-advanced
So per. default is not implemented.
