### ISSUE TITLE
Integration configuration

### ISSUE THREAD

**Issue by andrei-svistunou** [queueit/KnownUser.V3.Javascript#5]
Hi all,

I'm in progress with implementation QueueIt using NodeJs SDK and have one question: is it possible to get Integration Configuration, not from a local file, but making API call to QueueIT provider by customerId?

Thank you in advance.

**Comment by frwiqueueit** [comment]
Yes its possible. Please refer to our documentation page for how this is done.
https://github.com/queueit/Documentation/tree/main/serverside-connectors/integration-config
Its important to note that downloading this config file should NOT happen as part of normal request handling, but in some background process.
